[workspace]

members = [
  "crates/turbo-tasks",
  "crates/turbo-tasks-memory",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-build",
  "crates/turbo-tasks-fs",
  "crates/turbopack",
  "crates/node-file-trace",
]
