[workspace]

members = [
  "packages/turbo-tasks",
  "packages/turbo-tasks-macros",
  "packages/turbo-tasks-example",
  "packages/turbo-tasks-fs",
  "packages/turbo-pack",
  "packages/node-file-trace",
]
