[workspace]
resolver = "2"

members = [
  "crates/turbo-tasks",
  "crates/turbo-tasks-memory",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-build",
  "crates/turbo-tasks-fs",
  "crates/turbo-tasks-rocksdb",
  "crates/turbo-tasks-testing",
  "crates/turbopack",
  "crates/turbopack-core",
  "crates/turbopack-css",
  "crates/turbopack-ecmascript",
  "crates/turbopack-dev-server",
  "crates/node-file-trace",
  "crates/next-dev",
]
