[profile.release]
debug = true
split-debuginfo = "packed"

[workspace]

members = [
  "crates/turbo-tasks",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-fs",
  "crates/turbopack",
  "crates/node-file-trace",
]
