[workspace]
resolver = "2"

members = [
  "crates/turbo-malloc",
  "crates/turbo-tasks",
  "crates/turbo-tasks-memory",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-build",
  "crates/turbo-tasks-fs",
  "crates/turbo-tasks-test-utils",
  "crates/turbo-tasks-testing",
  "crates/turbopack",
  "crates/turbopack-core",
  "crates/turbopack-css",
  "crates/turbopack-ecmascript",
  "crates/turbopack-dev-server",
  "crates/turbopack-cli-utils",
  "crates/node-file-trace",
  "crates/next-dev",
  "crates/xtask",
  "crates/swc-ast-explorer",
]

[profile.release]
# We use CARGO_PROFILE_RELEASE_LTO instead
# lto = true

[profile.bench]
# We want correct benchmark results
lto = true

[profile.dev.package.turbo-tasks-macros]
opt-level = 3

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 3
