[profile.release]
debug = 1

[workspace]

members = [
  "crates/turbo-tasks",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-example",
  "crates/turbo-tasks-fs",
  "crates/turbo-pack",
  "crates/node-file-trace",
]
