packages:
  - "packages/*"
  - "packages/turbo-tracing-next-plugin/test/with-mongodb-mongoose"
  - "crates/turbopack/tests/node-file-trace"
  - "crates/turbopack/tests/snapshot"
  - "crates/next-dev/tests"
