name: "Turborepo Build Debug"
description: "Builds debug version of turborepo"
inputs:
  target:
    description: "Compilation target"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: "Setup Node"
      uses: ./.github/actions/setup-node
    - name: "Setup Go"
      uses: ./.github/actions/setup-go
    - name: "Setup Rust toolchain"
      uses: actions-rs/toolchain@v1
    - name: "Setup Rust Cache"
      uses: Swatinem/rust-cache@v2
      with:
        key: debug-${{ inputs.target }}
    - name: Build Turborepo
      run: cargo build --bin shim
