name: Benchmark PR

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_RELEASE_LTO: true

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: Swatinem/rust-cache@v1
        with:
          key: benchmark

      - name: Run cargo build benches (main)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: build
          args: --benches --release

      - name: Run cargo bench (main)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: bench
          args: -- --save-baseline=main

      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Run cargo build benches (PR)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: build
          args: --benches --release

      - name: Run cargo bench (PR)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: bench
          args: -- --save-baseline=pr

      - name: Show results
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: -- --load-baseline=pr --baseline=main

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: benchmark report
          path: target/criterion/
