name: Benchmark

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_RELEASE_LTO: true
  RUST_BACKTRACE: 1
  TURBOPACK_BENCH_ALL: 1

jobs:
  bench:
    runs-on: ubuntu-latest-16-core

    steps:
      - uses: actions/checkout@v3

      - name: install node.js dependencies
        run: yarn install

      - uses: Swatinem/rust-cache@v1
        with:
          key: benchmark

      - name: Run cargo bench
        uses: actions-rs/cargo@v1
        timeout-minutes: 60
        with:
          command: bench

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: benchmark report
          path: target/criterion/
