name: Benchmark

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_RELEASE_LTO: true

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          key: benchmark

      - name: Run cargo bench
        uses: actions-rs/cargo@v1
        with:
          command: bench

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: benchmark report
          path: target/criterion/
