name: Benchmark PR

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_RELEASE_LTO: true
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{  github.event_name == 'pull_request' }}

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: Swatinem/rust-cache@v1
        with:
          key: benchmark

      - uses: boa-dev/criterion-compare-action@v3.2.2
        with:
          branchName: ${{ github.base_ref }}

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: benchmark report
          path: target/criterion/
