name: Build release

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install target
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-musl

      - uses: Swatinem/rust-cache@v1
        with:
          key: release

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p node-file-trace --target=x86_64-unknown-linux-musl

      - uses: actions/upload-artifact@v3
        with:
          name: node-file-trace
          path: target/x86_64-unknown-linux-musl/release/node-file-trace
