name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          key: check

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features persistent_cache

      - name: Run cargo check tests
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --tests --features test_persistent_cache

      - name: Run cargo check examples
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --examples

      - name: Run cargo check benches
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --benches

      - name: Install cargo clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # args: -- -D warnings

      - name: Install cargo rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
