name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish the Docker image to DockerHub
      uses: gythialy/Publish-Docker-Github-Action@master
      with:
        name: goreng/golang-cross
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Publish the Docker image to GitHub Packages
      uses: gythialy/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/gythialy/golang-cross/xcgo
        username: gythialy
        password: ${{ secrets.DEPLOY_TOKEN }}
        registry: docker.pkg.github.com
      if: success()