name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
    
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # args: -- -D warnings
