name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo check tests
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --tests

      - name: Run cargo check examples
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --examples

      - name: Run cargo check benches
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --benches

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run cargo build tests
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests

      - name: Run cargo build examples
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples

      - name: Run cargo build benches
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --benches

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: |
            crates/turbopack/tests/node-file-trace/yarn.lock
          node-version: 16

      - run: yarn install --frozen-lockfile
        working-directory: crates/turbopack/tests/node-file-trace

      - name: Install nextest
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-nextest

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run

      - name: Run cargo test (benchmarks)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --benches

      - name: Install cargo clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # args: -- -D warnings
