name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          key: test

      - name: Run cargo build tests
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests --release

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: |
            crates/turbopack/tests/node-file-trace/yarn.lock
          node-version: 16

      - run: yarn install --frozen-lockfile
        working-directory: crates/turbopack/tests/node-file-trace

      - name: Install nextest
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-nextest

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --release

      - name: Run cargo test (benchmarks)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --benches
